# Backend (important for Pi)
backend = "glx";
vsync = true;

# Performance tuning
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

# Shadows (disable for clean HMI look)
shadow = false;

# Fading (keep subtle)
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Transparency
inactive-opacity = 0.95;
active-opacity = 1.0;
frame-opacity = 1.0;

# Rounded corners
corner-radius = 12;

# Blur (disable on Raspberry Pi)
blur:
{
  method = "none";
};

# Focus
mark-wmwin-focused = true;
mark-ovredir-focused = true;

# Exclude bar from transparency/rounding
rounded-corners-exclude = [
  "class_g = 'Qtile'",
];

opacity-rule = [
  "100:class_g = 'Qtile'"
];